# fly.toml app configuration file generated for legion-backend on 2025-12-02T13:36:09+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'legion-backend'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  LOG_LEVEL = 'info'
  NODE_ENV = 'production'
  PORT = '3000'
  USE_DEMO = 'true'
  USE_EONET = 'true'
  USE_GDELT = 'true'
  USE_RSS = 'true'
  USE_USGS = 'true'

[[services]]
  protocol = 'tcp'
  internal_port = 3000

  [[services.ports]]
    port = 3000

[[vm]]
  size = 'shared-cpu-1x'
